### ISSUE TITLE
Widget target code not executing

### ISSUE THREAD

**Issue by carozo** [EvanBacon/expo-apple-targets#45]
Hi! I’m using the plugin to create a widget target for my app (we want to use Live Activities). While the target is being generated correctly and the Live Activity is being requested, the UI code in the widget’s ActivityConfiguration is never executed (index.swift). The main target file doesn’t seem to run, and I’m not seeing any errors and the target was created in Xcode.

I have an Attributes.swift file in both the expo module that I created to call the live activity (which is running OK) and inside targets/widget.

Any help would be greatly appreciated. Thank you!

Expo SDK: 51.0.34
iOS Version: 17.5
Xcode Version: 15.4

**Comment by enterteg** [comment]
@carozo Are you sure the LA params in expo module and in Attributes.swift are exactly the same? You can use Console.app to see logs. For me Activity is properly showing up but it's not being executed either so that shouldn't be an issue.

**Comment by carozo** [comment]
@enterteg thank you for your answer.

Actually I got it to work by moving the Attributes object to the same Swift file in which I had the widget code and the expo module swift code (removed both Attributes.swift files). It was very strange, as the file appeared on the compile source files of the target. Maybe the issue of not finding the Attributes was on the module's side and not the target. 

But if anyone runs into the same issue, moving the Attributes into the same swift file might be worth a try.
